### ISSUE TITLE
How to proceed with this case?

### ISSUE THREAD

**Issue by luiguild** [tunnckoCore/load-deps#4]
Hi, I will use this three packages just simple examples

```
gulp-csscomb-lint
gulp-live-server
gulp-pug-lint
gulp-clean-css
```

does not make sense strip names using:

```
let stripDeps = ['gulp', 'csscomb', 'live', 'pug', 'clean'];
let renameDeps = function renameFn(name) {
    return nameDeps(name, stripDeps);
};

let $ = loadDeps('*', {
    renameKey: renameDeps
});
```

To using them: 

```
$.lint();
$.server();
$.lint(); (?)
$.css();
```

How can I proceed to use them?

**Comment by tunnckoCore** [comment]
Hi. Why not just strip the gulp, then camelCase them? So...

```
$.csscombLint();
$.liveServer();
$.pugLint();
$.cleanCss();
```

**Comment by luiguild** [comment]
If I try use the name with camelCase:
```
const liveServer = $.liveServer.static(server.folder, server.port);
TypeError: Cannot read property 'static' of undefined
```

And for the others packages gulp return an error also...

:(

**Comment by luiguild** [comment]
If I try use the name with camelCase:

const liveServer = $.liveServer.static(server.folder, server.port);
TypeError: Cannot read property 'static' of undefined

And for the others packages gulp return an error also...

:(

**Comment by luiguild** [comment]
If I try use the name with camelCase:

```
const liveServer = $.liveServer.static(server.folder, server.port);
TypeError: Cannot read property 'static' of undefined
```

And for the others packages gulp return an error also...

:(

**Comment by luiguild** [comment]
```
$.cleanCss is not a function
```

**Comment by tunnckoCore** [comment]
That's normal man. I meant to use some camelcasing (or package) in that renameFn.

``` js
let camelcase = require('camelcase')
let appname = require('app-name')
let loadDeps = require('load-deps')

let rename = function renameFn (name) {
  return camelcase(appname(name, ['gulp']))
}

let $ = loadDeps('*', {
    renameKey: rename
})
```

**Comment by tunnckoCore** [comment]
@luiguild, also you can just use Jon's `load-plugins`, because there are these things built in. But this is pretty faster than it and with lower dependencies.
