### ISSUE TITLE
I cant load a dependence

### ISSUE THREAD

**Issue by luiguild** [tunnckoCore/load-deps#5]
I'm trying use this package > https://www.npmjs.com/package/gulp-pug (Gulp-Pug)

But the task broke and load-deps say that:

```
$.pug is not a function
```

You can help me to resolve this?
Actually I keep declaring the package manually

```
let pug = require('gulp-pug');
```

Thanks! ❤️

**Comment by tunnckoCore** [comment]
You just not using this module correctly. See my response in the #4 issue.

**Comment by tunnckoCore** [comment]
This package just loads (gives you) that `devDependencies` object as result. They you can just use them. If there are some special characters you should access them as in normal javascript world.

``` js
var obj = {
  'beta': 'alpha'
  'foo-bar-baz': 'qux'
}

console.log(obj)
console.log(obj.beta)
console.log(obj['foo-bar-baz'])
```
